# This is a reusable GitHub Action workflow for testing a package PR on buildout.coredev.
# For now (May 2022) it is an experiment, but I (Maurits) think we need it.
# Reasons:
# 1. The robot tests on Jenkins are flaky/unstable, which most likely is due
#    to several robot jobs running parallel on one node.
# 2. Python 3.10 is not working with the 'Python Shining Pandas' plugin we use
#    on Jenkins.  We had it running with a different script for a while, but
#    these changes got lost.  Should be restorable, but let's try GHA.
#
# One thing to watch out for, is that robot tests are not always reported as failures.
# On the one hand there is config for that on Jenkins:
# https://github.com/plone/jenkins.plone.org/issues/297
# On the other hand I see the same problem locally:
# https://github.com/plone/Products.CMFPlone/issues/3537

# The first user of this reusable workflow is:
# https://github.com/plone/Products.CMFPlone/pull/3540
# See there for the few lines you need.
# More on reusable workflows:
# https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: Test on buildout.coredev.
# This makes us a reusable workflow:
on: workflow_call
# Note: the caller workflow *must* use 'on: pull_request'
jobs:
  package:
    name: Run tests of the package itself, on lowest and highest Python version.
    uses: ./.github/workflows/coredev-60.yml
    with:
      # For the used syntax, see
      # https://github.community/t/reusable-workflow-with-strategy-matrix/205676/8
      python-version: >-
        ["3.7", "3.10"]
      # Note: if the unit tests (without layers) fail, we do not want to start the others.
      test-command: |
        bin/test -s ${{ github.event.repository.name }} -u
        bin/test -s ${{ github.event.repository.name }}

  test:
    # The "package" job shouldfinish successfully first.
    needs: package
    name: Run unit and other standard tests of all packages.
    uses: ./.github/workflows/coredev-60.yml
    with:
      python-version: "3.10"
      # Note: if the unit tests (without layers) fail, we do not want to start the others.
      test-command: |
        bin/test -u
        bin/test

  robot:
    # The "test" job should finish successfully first.
    needs: test
    name: Run robot tests of all packages.
    uses: ./.github/workflows/coredev-60.yml
    with:
      python-version: "3.10"
      # There could be a nicer way to say "only robot tests please",
      # but the convention of putting all robot tests in test_robot.py helps.
      test-command: "bin/test --all -m test_robot"
